<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="BackgroundComm" Id="{40779a71-740b-4a35-a3c1-34d5abe4afe3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM BackgroundComm
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[HWVar.ModbusMaster();]]></ST>
    </Implementation>
    <LineIds Name="BackgroundComm">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>