<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.9">
  <POU Name="MQTTComm" Id="{efe7e652-d626-4d55-97a9-285f5546527a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MQTTComm
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MQTTComm">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>